"""Add models

Revision ID: 0b641a99f886
Revises: 38a99cbd056d
Create Date: 2025-03-05 20:46:55.956380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b641a99f886'
down_revision: Union[str, None] = '38a99cbd056d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod_env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pod.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_env_pod_id'), 'pod_env', ['pod_id'], unique=False)
    op.create_index(op.f('ix_pod_env_user_id'), 'pod_env', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pod_env_user_id'), table_name='pod_env')
    op.drop_index(op.f('ix_pod_env_pod_id'), table_name='pod_env')
    op.drop_table('pod_env')
    # ### end Alembic commands ###
