"""add fields to Pod

Revision ID: 1c2d8b788e04
Revises: 3064ca80b242
Create Date: 2025-03-01 14:05:10.464930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c2d8b788e04'
down_revision: Union[str, None] = '3064ca80b242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pod', sa.Column('container_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('pod', sa.Column('port', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pod', 'port')
    op.drop_column('pod', 'container_image')
    # ### end Alembic commands ###
