"""Re ReservedPort model

Revision ID: 38a99cbd056d
Revises: d76a447dffa2
Create Date: 2025-03-05 19:28:13.456521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38a99cbd056d'
down_revision: Union[str, None] = 'd76a447dffa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserved_port', sa.Column('external_port', sa.Integer(), nullable=False))
    op.drop_constraint('reserved_port_port_key', 'reserved_port', type_='unique')
    op.create_unique_constraint(None, 'reserved_port', ['external_port'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserved_port', type_='unique')
    op.create_unique_constraint('reserved_port_port_key', 'reserved_port', ['port'])
    op.drop_column('reserved_port', 'external_port')
    # ### end Alembic commands ###
