"""New models

Revision ID: 7cc70cb364ea
Revises: 7972876dad46
Create Date: 2025-02-28 15:08:32.670673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7cc70cb364ea'
down_revision: Union[str, None] = '7972876dad46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_storage_user_id'), 'storage', ['user_id'], unique=False)
    op.create_table('pod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_pod_storage_id'), 'pod', ['storage_id'], unique=False)
    op.create_index(op.f('ix_pod_user_id'), 'pod', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pod_user_id'), table_name='pod')
    op.drop_index(op.f('ix_pod_storage_id'), table_name='pod')
    op.drop_table('pod')
    op.drop_index(op.f('ix_storage_user_id'), table_name='storage')
    op.drop_table('storage')
    # ### end Alembic commands ###
