"""Alter storage_id

Revision ID: aec681689bb8
Revises: 0b641a99f886
Create Date: 2025-03-06 04:41:33.896286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aec681689bb8'
down_revision: Union[str, None] = '0b641a99f886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pod', 'storage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pod', 'storage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
