"""Add ReservedPort model

Revision ID: d76a447dffa2
Revises: 1c2d8b788e04
Create Date: 2025-03-05 18:44:43.395556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd76a447dffa2'
down_revision: Union[str, None] = '1c2d8b788e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserved_port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pod.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port')
    )
    op.create_index(op.f('ix_reserved_port_pod_id'), 'reserved_port', ['pod_id'], unique=False)
    op.create_index(op.f('ix_reserved_port_user_id'), 'reserved_port', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserved_port_user_id'), table_name='reserved_port')
    op.drop_index(op.f('ix_reserved_port_pod_id'), table_name='reserved_port')
    op.drop_table('reserved_port')
    # ### end Alembic commands ###
